$(document).ready ->
  # Add smooth scrolling to all links
  $('a').on 'click', (event) ->
    # Make sure this.hash has a value before overriding default behavior
    if @hash != ''
      # Prevent default anchor click behavior
      event.preventDefault()
      # Store hash
      hash = @hash
      # Using jQuery's animate() method to add smooth page scroll
      # The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate { scrollTop: $(hash).offset().top }, 800, ->
        # Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash
        return
    # End if
    return
  $(document).ready ->
    # Mobile nav-bar
    $('#nav-mobile').html $('#nav-main').html()
    $('#nav-trigger i').click ->
      if $('nav#nav-mobile a').hasClass('expanded')
        $('nav#nav-mobile a.expanded').removeClass('expanded').slideUp 250
        $(this).removeClass 'open'
      else
        $('nav#nav-mobile a').addClass('expanded').slideDown 250
        $(this).addClass 'open'
      return
    # Resizes nav-bar on scroll
    $ ->
      $('#nav-main').data 'size', 'big'
      return
    $(window).scroll ->
      if $(document).scrollTop() > 0
        if $('#nav-main').data('size') == 'big'
          $('#nav-main').data 'size', 'small'
          $('#nav-main').stop().animate {
            'height': '50px'
            'padding-right': '4em'
            'padding-left': '4em'
          }, 600
          $('#nav-main').addClass 'sticky-nav-bar'
          $('.slider').addClass 'slider-animate'
          $('.left-side img').animate { 'width': '40px' }, 600
      else
        if $('#nav-main').data('size') == 'small'
          $('#nav-main').data 'size', 'big'
          $('#nav-main').stop().animate {
            'height': '100px'
            'padding-right': '4em'
            'padding-left': '4em'
          }, 600
          $('#nav-main').removeClass 'sticky-nav-bar'
          $('.slider').removeClass 'slider-animate'
          $('.left-side img').animate { 'width': '50px' }, 600
      return
    return
  # Plays with slider on scroll
  lastScrollTop = 0
  $(window).scroll (event) ->
    st = $(this).scrollTop()
    if st > lastScrollTop
      $('.slider').addClass 'slider-animate'
    else
      $('.slider').removeClass 'slider-animate'
    lastScrollTop = st
    return
  return

# ---
# generated by js2coffee 2.2.0
